"use strict";

const Process = require("process");
const DevkitBaseError = require("./devkit-base-error.js");

class ChildProcessError extends DevkitBaseError {

  /**
   * `ChildProcessError` class for representing errors that occur when a child process fails.
   * 
   * @class
   * @classdesc Represents an error when a child process encounters an error or exits unexpectedly.
   * @param {string} message - A description of the error.
   * @param {*} [cause=null] - The underlying cause of the error (optional).
   * @extends {DevkitBaseError}
   */
  constructor(message, cause = null) {
    const taskName = (Process.argv[2] && Process.argv[2].replace(/-[a-z]/g, match => { 
      return match[1].toUpperCase();
    })) || "_init";

    super(message + `\n  This is probably not a problem with "uu_cloudg02-devkit ${taskName}" task itself. There is likely additional logging output above.`, null, cause);
    this.name = "ChildProcessError";
  }

}

module.exports = ChildProcessError;
